2021/09/15 19:59:18 Starting App Insight Logger for task:  runTaskLet
2021/09/15 19:59:18 Version: 3.0.01706.0003 Branch: 2021-09-03 Commit: cd0f702
2021/09/15 19:59:18 Attempt 1 of http call to http://10.0.0.6:16384/sendlogstoartifacts/info
2021/09/15 19:59:18 Send process info logs to master server succeeded
2021/09/15 19:59:18 Attempt 1 of http call to http://10.0.0.6:16384/sendlogstoartifacts/status
2021/09/15 19:59:18 Send process info logs to master server succeeded
[2021-09-15T19:59:18.326956] Entering context manager injector.
[2021-09-15T19:59:18.655165] context_manager_injector.py Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError'], invocation=['train.py', '--C', '0.3562308188493205', '--max_iter', '100'])
Script type = None
[2021-09-15T19:59:18.658942] Entering Run History Context Manager.
[2021-09-15T19:59:19.328217] Current directory: /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-158411/azureml/hd_575e8263-4182-4bb3-9071-e6222c35e333_7/wd/azureml/HD_575e8263-4182-4bb3-9071-e6222c35e333_7
[2021-09-15T19:59:19.328427] Preparing to call script [train.py] with arguments:['--C', '0.3562308188493205', '--max_iter', '100']
[2021-09-15T19:59:19.328453] After variable expansion, calling script [train.py] with arguments:['--C', '0.3562308188493205', '--max_iter', '100']

2021/09/15 19:59:23 Not exporting to RunHistory as the exporter is either stopped or there is no data.
Stopped: false
OriginalData: 1
FilteredData: 0.
/opt/miniconda/lib/python3.6/site-packages/azureml/dataprep/api/dataflow.py:722: UserWarning: Your pandas and pyarrow versions are incompatible. Please install pyarrow>=0.12.0 for improved performance of to_pandas_dataframe. You can ensure the correct version is installed by running: pip install pyarrow>=0.12.0 --upgrade
  warnings.warn('Your pandas and pyarrow versions are incompatible. '
/opt/miniconda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[2021-09-15T19:59:27.588301] The experiment completed successfully. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
2 items cleaning up...
Cleanup took 5.447335958480835 seconds
[2021-09-15T19:59:33.108287] Finished context manager injector.
2021/09/15 19:59:33 Attempt 1 of http call to http://10.0.0.6:16384/sendlogstoartifacts/status
2021/09/15 19:59:33 Send process info logs to master server succeeded
2021/09/15 19:59:33 Not exporting to RunHistory as the exporter is either stopped or there is no data.
Stopped: false
OriginalData: 2
FilteredData: 0.
2021/09/15 19:59:33 Process Exiting with Code:  0
2021/09/15 19:59:34 All App Insights Logs was sent successfully or the close timeout of 10 was reached
